services:
    core:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: core
        command: python main.py
        volumes:
            - ./core:/app
        env_file:
            - ./.env
        restart: always
